(setq-default frame-background-mode 'dark)
(setq frame-inhibit-implied-resize t)
(add-to-list 'default-frame-alist '(width . 100))
(add-to-list 'default-frame-alist '(height . 50))
(add-to-list 'default-frame-alist '(font . "Fira Mono-12"))
(setq package-enable-at-startup nil)
